### ISSUE TITLE
User used to connect requires access to _system database

### ISSUE THREAD

**Issue by SitiSchu** [guoli-lyu/arangors#3]
When trying to connect to arangodb without the user having access to `_system` arangors will fail with `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "not authorized to execute this request" }', src/libcore/result.rs:999:5`

In the requests logs this shows up as `"GET","HTTP/1.1",401,0,95,"/_api/database/user",0.000039` 

I can connect just fine using arangosh and pyArango without giving the user access to `_system` so is this request really necessary? 

The code is copied from the example: `Connection::establish_basic_auth("http://localhost:8529", "username", "password").unwrap();` (replaced with the proper credentials)

**Comment by guoli-lyu** [comment]
This is a known issue I am working on. I am removing the caching behaviour for collections too.

**Comment by guoli-lyu** [comment]
This issue has been fix in v0.2. Feel free to have a try.
