### ISSUE TITLE
Could Clone be added to Connection?

### ISSUE THREAD

**Issue by davechallis** [guoli-lyu/arangors#4]
It would sometimes be useful to be able to clone a `Connection` after it's been created, and collections fetched etc.

All of its member structs are cloneable, so should just be a case of adding `derive(Clone)` to `Database` and `Connection` structs.

But perhaps there's a good reason not to, I'm not that familiar with the codebase yet.

**Comment by guoli-lyu** [comment]
With current caching behaviour, this is impossible. Each connection stores a hashmap of databases, which should never be cloned.

Currently, the best way is to setup another Connection.

**Comment by davechallis** [comment]
Thanks, that makes sense.
